name: 'Resolve Inventory'
description: 'Fetches additional information for software artifacts listed in an inventory using metaeffekt-kontinuum'
author: '{metaeffekt} GmbH'

inputs:
  cache-dependencies:
    description: 'Cache dependencies to speed up subsequent runs, as well as all other actions contained in this repo.'
    required: false
    default: 'false'
  input-path:
    description: 'Path to the input inventory file to resolve.'
    required: true
  output-path:
    description: 'Path where the resolved inventory will be saved.'
    required: true
  resolver-config:
    description: 'Path to the artifact resolver config file.'
    required: false
    default: ${{ github.action_path }}/../shared/artifact-resolver-config.yaml
  resolver-proxy:
    description: 'Path to the proxy config file for the resolver.'
    required: false
    default: ${{ github.action_path }}/../shared/artifact-resolver-proxy.yaml

outputs:
  resolved-inventory:
    description: 'Path to the resolved inventory file'
    value: ${{ inputs.output-path }}

runs:
  using: composite
  steps:
    - name: Setup metaeffekt-kontinuum
      id: setup-kontinuum
      uses: ./setup-kontinuum
      with:
        cache-dependencies: ${{ inputs.cache-dependencies }}

    - name: Resolve inventory
      id: resolve
      shell: bash
      run: |
        echo "Resolving inventory: ${{ inputs.input-path }} -> ${{ inputs.output-path }}"
        echo "Using metaeffekt-kontinuum version ${{ steps.setup-kontinuum.outputs.kontinuum-version }}"
        
        if ! command -v mvn &> /dev/null; then
          echo "::error::Maven is not available. Please ensure Java and Maven are installed."
          exit 1
        fi
        
        mkdir -p "/tmp/downloads"
        
        cp "${{ steps.setup-kontinuum.outputs.kontinuum-path }}/ae-workbench-parent.xml" .
        cp "${{ steps.setup-kontinuum.outputs.kontinuum-path }}/analyze_resolve-inventory.xml" .
        
        mvn -f "analyze_resolve-inventory.xml" process-resources \
          -DinputInventoryFile="${{ inputs.input-path }}" \
          -DoutputInventoryFile="${{ inputs.output-path }}" \
          -DdownloadBaseDir="/tmp/downloads" \
          -DartifactResolverConfig="${{ inputs.resolver-config }}" \
          -DproxyConfig="${{ inputs.resolver-proxy }}" \
        
        rm -f ae-workbench-parent.xml analyze_resolve-inventory.xml