name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.2.3)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean
      update-major-tag:
        description: 'Update major version tag (e.g., 1)'
        required: false
        default: true
        type: boolean

jobs:
  validate:
    name: Validate Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.validate.outputs.version }}
      version-tag: ${{ steps.validate.outputs.version-tag }}
      major-version: ${{ steps.validate.outputs.major-version }}
      minor-version: ${{ steps.validate.outputs.minor-version }}

    steps:
      - name: Validate version format
        id: validate
        run: |
          VERSION="${{ github.event.inputs.version }}"

          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format. Use 'X.Y.Z'."
            exit 1
          fi

          # Extract version components
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)

          MAJOR_TAG="$MAJOR"
          MINOR_TAG="$MAJOR.$MINOR"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version-tag=$VERSION" >> $GITHUB_OUTPUT
          echo "major-version=$MAJOR_TAG" >> $GITHUB_OUTPUT
          echo "minor-version=$MINOR_TAG" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/${{ steps.validate.outputs.version-tag }}$"; then
            echo "::error::Tag ${{ steps.validate.outputs.version-tag }} already exists"
            exit 1
          fi

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --local user.name "ae-actions-runner"
          git config --local user.email "ae-actions-runner@metaeffekt.com"

      - name: Update action references
        id: update-refs
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          VERSION_TAG="${{ needs.validate.outputs.version-tag }}"
          REPO_NAME="${{ github.repository }}"
          
          echo "Updating action references from @main to @$VERSION_TAG"
          
          UPDATED_FILES=()
          
          find . -name "action.yml" -not -path "./.git/*" | while read action_file; do
          
            if grep -q "uses: $REPO_NAME/.*@main" "$action_file"; then
          
              sed -i "s|uses: $REPO_NAME/\([^@]*\)@main|uses: $REPO_NAME/\1@$VERSION_TAG|g" "$action_file"
          
              echo "  Updated: $action_file"
              echo "$action_file" >> /tmp/updated_files.txt
            fi
          done
          
          if [[ -f /tmp/updated_files.txt ]]; then
            echo "updated=true" >> $GITHUB_OUTPUT
            echo "Files updated:"
            cat /tmp/updated_files.txt
          else
            echo "updated=false" >> $GITHUB_OUTPUT
            echo "No files needed updating"
          fi

      - name: Commit version updates
        if: steps.update-refs.outputs.updated == 'true'
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          VERSION_TAG="${{ needs.validate.outputs.version-tag }}"
          
          git add -A
          
          if ! git diff --staged --quiet; then
            git commit -m "Release $VERSION: Update action references from @main to @$VERSION_TAG"
            echo "Changes committed"
          else
            echo "No changes to commit"
          fi

      - name: Create and push release tag
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          VERSION_TAG="${{ needs.validate.outputs.version-tag }}"
          
          git tag -a "$VERSION_TAG" -m "Release $VERSION"
          git push origin "$VERSION_TAG"
          
          echo "Created and pushed tag: $VERSION_TAG"

      - name: Update major and minor version tags
        if: github.event.inputs.update-major-tag == 'true'
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          MAJOR_VERSION="${{ needs.validate.outputs.major-version }}"
          MINOR_VERSION="${{ needs.validate.outputs.minor-version }}"
          
          git tag -f "$MAJOR_VERSION"
          git push origin "$MAJOR_VERSION" --force
          
          git tag -f "$MINOR_VERSION"
          git push origin "$MINOR_VERSION" --force

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.validate.outputs.version-tag }}
          release_name: ${{ needs.validate.outputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}